### ISSUE TITLE
Uncaught ReferenceError: resolve is not defined

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#49] opened 2016-02-15 17:19 UTC
Hello,

I am on a windows 7 machine running the latest stable versions of atom, purescript, pulp and pci-ide as recommended in the readme.  In my ide-purescript settings, I have "build on save" unchecked.  Every time I click the save button, I receive this error:  `Uncaught ReferenceError: resolve is not defined`.  This happens every single time a file is saved.  If I enable "build on save", the error goes away but I am stuck dealing with slow recompilation builds every time I re-save a file which is not practical.  Here is the stack trace:

```
**Atom Version**: 1.5.3
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.8.2


### Stack Trace

Uncaught ReferenceError: resolve is not defined

At C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:825

ReferenceError: resolve is not defined
    at LinterPurescript.lintOnSave (file:///C:/Users/Adam/.atom/packages/ide-purescript/lib/linter-purescript.coffee:68:7)
    at LinterPurescript.lintOnSave (file:///C:/Users/Adam/.atom/packages/ide-purescript/lib/linter-purescript.coffee:1:1)
    at file:///C:/Users/Adam/.atom/packages/ide-purescript/lib/editors.coffee:21:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Adam\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  9x -0:42.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:37 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:30.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:backspace (atom-text-editor.editor.is-focused)
 11x -0:22.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:21 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:11.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:09.0 core:save (atom-text-editor.editor.is-focused)
```

Any ideas?

**Comment by nwolverson** [comment] 2016-02-15 19:55
Sorry, this looks like a duplicate of #46, I didn't make a release. Should be fixed now (new release 0.8.4 pushed out).

**Closed as completed by nwolverson** 2016-02-15 19:55 UTC
