### ISSUE TITLE
'Unknown module' bug?

### ISSUE THREAD

**Issue by adkelley** [nwolverson/atom-ide-purescript#145] opened 2017-02-02 01:23 UTC
This bug keeps cropping up in my purescript projects in the atom editor.  The first import statement after` import Prelude` is flagged as a Purescript Error.  If there are no imports besides Prelude, the` import Prelude` statement is flagged as an error. 

This is in spite having the library loaded in bower_components and listed in my bower.json file and `pulp build` runs fine.  I would appreciate any ideas on how to make it go away.

**Comment by sudhirvkumar** [comment] 2017-02-02 07:02
@adkelley When I get that, 

I usually close my editor.
Delete output folder, run `pulp build` and then start editor and things work fine. Most of the time, there is some error in the code somewhere.

**Comment by nwolverson** [comment] 2017-02-02 10:36
In general these issues will be due to invalid project externs in output. You should be able to rebuild and run restart psc-ide-server command inside the editor without restarting it, to the same effect.

There's some work in the future to properly handle this situation (psc-ide will tell us when the project needs rebuilt) but that's at an initial stage so far

**Comment by adkelley** [comment] 2017-02-02 17:12
@sudhirvkumar @nwolverson  Thank you!

**Comment by nwolverson** [comment] 2017-02-10 10:37
Closing as duplicate of #128

**Closed as completed by nwolverson** 2017-02-10 10:37 UTC
