### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dariooddenino** [nwolverson/atom-ide-purescript#108] opened 2016-07-18 18:37 UTC
Hi,
I can'use ide-purescript :(
I get error messages as soon as I import a project.
1. Generate a new project with `pulp init`
2. Open it 
3. That's it.

I'm on windows 10 64 bit.

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.14.2
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:1604

TypeError: Cannot read property 'length' of undefined
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:1604:53
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:1666:71
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:10510:113
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:2621:23
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:2577:7
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:2621:27
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:2655:11
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:2566:13
    at C:\Users\Utente\.atom\packages\ide-purescript\lib\main.js:10329:25
    at F (C:\Users\Utente\.atom\packages\ide-purescript\node_modules\which\which.js:69:16)
    at E (C:\Users\Utente\.atom\packages\ide-purescript\node_modules\which\which.js:81:29)
    at C:\Users\Utente\.atom\packages\ide-purescript\node_modules\which\which.js:90:16
    at C:\Users\Utente\.atom\packages\ide-purescript\node_modules\which\node_modules\isexe\index.js:44:5
    at C:\Users\Utente\.atom\packages\ide-purescript\node_modules\which\node_modules\isexe\windows.js:29:5
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -6:55.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -5:55.7.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {},
  "ide-purescript": {
    "fastRebuild": true
  }
}
```
### Installed Packages

``` coffee
# User
ide-purescript, v0.14.2
language-haskell, v1.7.18
language-purescript, v0.7.0
linter, v1.11.14
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by nwolverson** [comment] 2016-07-18 21:10
Guessing you haven't had this working with an earlier version. 2 things, clearly there is a bug in the package but I think you're hitting a case where you don't have `psc-ide-server` in your path. If you installed from npm, this means that your npm bin dir where `psc-ide-server.cmd` resides should be in `PATH`.

**Comment by nwolverson** [comment] 2016-07-18 21:49
I was able to reproduce and I have a fix for the incorrect error `Uncaught TypeError: Cannot read property 'length' of undefined`. However I think you will also have seen the other error around your `PATH` as above which you will need to fix in your environment.

**Comment by dariooddenino** [comment] 2016-07-18 21:53
`psc-ide-server.cmd` is in my path. I think that the issue is that it's defined as `Path` and not `PATH`

**Comment by nwolverson** [comment] 2016-07-18 22:01
Yes, I think that's an Atom issue that it must be `PATH`. Looks like that will be solved in 1.9.0 https://github.com/atom/atom/issues/11302

If you can't set the expected `PATH` variable you can also configure an explicit path for all commands in the package settings.

**Comment by dariooddenino** [comment] 2016-07-19 18:32
Manually setting the path for `psc-ide-server` made this error disappear too

**Comment by nwolverson** [comment] 2016-07-23 07:45
Fixed by https://github.com/kRITZCREEK/purescript-psc-ide/commit/ce8ba5f38841752f690973a522f128dcce5ab121 - I need to update bower.json and make a release.

**Comment by nwolverson** [comment] 2016-07-23 19:58
Closing as the bad error is now fixed, and the PATH/Path issue is related to the linked atom issue.

**Closed as completed by nwolverson** 2016-07-23 19:58 UTC
