### ISSUE TITLE
Unexpected end of input error

### ISSUE THREAD

**Issue by paulyoung** [nwolverson/atom-ide-purescript#81] opened 2016-06-12 01:20 UTC
I was refactoring some code and ran into this.

After fixing some of the type errors reported by `pulp build`, things started working again.

`Error running PureScript build command: Error: Unexpected end of input at Object.exports.error (/Users/py/.atom/packages/ide-purescript/lib/main.js:2285:12) at __do (/Users/py/.atom/packages/ide-purescript/lib/main.js:7895:74) at ChildProcess. (/Users/py/.atom/packages/ide-purescript/lib/main.js:7350:42) at emitTwo (events.js:87:13) at ChildProcess.emit (events.js:172:7) at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)`

**Comment by nwolverson** [comment] 2016-06-12 10:39
That's interesting. What versions of pulp/psc/(psa?) is this with?

I usually use quick rebuild but haven't seen any problems with the full build - but I'm not on 0.9 properly if that's what you're using.

**Comment by paulyoung** [comment] 2016-06-14 05:21
I was using:
- psc 0.9.1
- pulp 9.0.1
- psa 0.3.9
- node 6.2.1

**Comment by nwolverson** [comment] 2016-06-29 19:39
I've still not seen this yet. Were you using the default build command and running a full build?

**Comment by paulyoung** [comment] 2016-06-29 19:53
I think my build command was set to `npm run build -- --json-errors` and "Use fast rebuild" was not checked.

The `build` script just runs `pulp build`.

**Comment by nwolverson** [comment] 2016-07-18 08:20
Sorry, still can't reproduce. Did you see this again?

**Comment by paulyoung** [comment] 2016-07-20 16:40
I haven't, but have since been using Spacemacs more than Atom.

Feel free to close this if you like and I'll report back if I see it again.

**Comment by nwolverson** [comment] 2018-03-31 16:54
Closing per last comment.

**Closed as completed by nwolverson** 2018-03-31 16:54 UTC
Labels: bug, more-info
