### ISSUE TITLE
Server process running but types don't show up

### ISSUE THREAD

**Issue by paf31** [nwolverson/atom-ide-purescript#19] opened 2015-09-14 00:30 UTC
I can see the process loaded the right modules and is making queries, but type and completion queries always return zero results. Running queries on the console by hand seems to work fine.

**Comment by nwolverson** [comment] 2015-09-14 06:35
What versions? @kRITZCREEK changed the response format yesterday before releasing 0.1.0, I've just published a new version which will handle this - could you give it a go?

(Or if that doesn't work - try closing and reopening the `.purs` file)

**Comment by kritzcreek** [comment] 2015-09-16 14:50
This works for me with the new version.

**Comment by nwolverson** [comment] 2015-09-16 15:43
@paf31 would you mind retrying with the current version from atom package manager when you get a minute?

**Comment by paf31** [comment] 2015-09-16 17:50
The server starts and I don't see errors in the console, but all completion and type lookups still return no results.

**Comment by nwolverson** [comment] 2015-09-16 22:42
This might be like #20 or similar, I've published a new version that might resolve this for you. I think the completion/lookup was being filtered by a very small (empty?) set of modules. If that still doesn't work, an example PS project that fails would be good

**Comment by Softsapiens** [comment] 2015-10-06 12:12
I'm having the same problem with atom 1.0.19, and the last version available of all the plugins.

**Comment by nwolverson** [comment] 2015-10-06 12:37
Since I still can't reproduce:
- What OS are you on?
- I presume you don't see any popup notifications
- Any chance of pointing at a sample project which doesn't work for you
- Can you bring up the dev tools in atom and see if there is any pertinent information? Particularly should be able to see the query sent to `psc-ide` and whether that seems reasonable.

Can also try starting `psc-ide` manually before running atom (think it maybe has a debug output flag now)

**Comment by kritzcreek** [comment] 2015-10-06 13:29
You can start psc-ide-server with the --debug flag in the rootfolder of your project to get logs about requests and responses.

**Comment by Softsapiens** [comment] 2015-10-06 14:40
- I use OSX.
- Nop, I don't see any popup.
- my repo is https://github.com/Softsapiens/purepoc
- In dev tools console I only see msgs like:
  psc-ide Object {command: "type", params: Object}command: "type"params: Object__proto__: Object --> Object {result: Array[0], resultType: "success"}
  psc-ide.coffee:29 exited with code 0

Starting the server manually, do not even see any msg.
Perhaps de suggested debug flag helps.

**Comment by nwolverson** [comment] 2015-10-06 21:50
Do you have atom open in the project root?

![screen shot 2015-10-06 at 21 41 40](https://cloud.githubusercontent.com/assets/2770891/10321898/227b85c0-6c73-11e5-86aa-8266ba22811f.png)

Works for me. I've just published a new version (`0.6.1`) with some extra logged/notified info - might want to try that / the debug flag.

**Comment by Softsapiens** [comment] 2015-10-07 09:02
Nope, I opened just the file. Sorry, and thanks for the help!

**Comment by nwolverson** [comment] 2016-01-21 07:26
@paf31 did you ever get this working?

**Comment by nwolverson** [comment] 2016-03-19 13:36
Closing this with lack of activity, everything is pretty much different now, from the package, psc-ide, etc. If anybody has a similar issue with the current version please do open up a new issue with details.

**Closed as completed by nwolverson** 2016-03-19 13:36 UTC
